name: List Repository Files

on:
  push:
    branches:
      - main

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -R
