name: Supabase Deployment

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: https://bysigkrrzhdsgxgtiflk.supabase.co
      SUPABASE_ANON_KEY: ${{ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5c2lna3Jyemhkc2d4Z3RpZmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDM4NDgsImV4cCI6MjA2OTExOTg0OH0.-O8d9BCCB5HDhBxd1lGU-_4LXHROckjorrywrV0IDf8}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Do something with Supabase
        run: |
          echo "Supabase URL: $SUPABASE_URL"
          echo "Supabase Key length: ${#SUPABASE_ANON_KEY}"

          # Example: call supabase CLI or make curl requests here
          # curl -H "apikey: $SUPABASE_ANON_KEY" $SUPABASE_URL/rest/v1/your_table
