name: Supabase Test
on:
  workflow_dispatch:
on:
  push:
    branches:
      - main  # or your default branch

jobs:
  test-supabase:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: "https://bysigkrrzhdsgxgtiflk.supabase.co"
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5c2lna3Jyemhkc2d4Z3RpZmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDM4NDgsImV4cCI6MjA2OTExOTg0OH0.-O8d9BCCB5HDhBxd1lGU-_4LXHROckjorrywrV0IDf8"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test Supabase API
        run: |
          echo "Supabase URL is $SUPABASE_URL"
          echo "Trying to fetch tables from Supabase..."

          curl -H "apikey: $SUPABASE_ANON_KEY" \
               -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
               "$SUPABASE_URL/rest/v1/information_schema.tables?select=table_name"
